phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      -  echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  
      - echo Installing source NPM dependencies...
      - npm install
      - npm install unit.js
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - mocha test.js
  post_build:
    commands:
      - echo Build completed on `date`
