version: 0.2

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - echo "Running unit tests"
      - npm test

  build:
    commands:
      - echo "Building the Docker image"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
